apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ikj6o8tnz-nodejs
  janus-idp.io/tekton: ikj6o8tnz-nodejs
  backstage.io/kubernetes-id: ikj6o8tnz-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ikj6o8tnz-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
