apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ikj6o8tnz-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ikj6o8tnz-nodejs 
  name: ikj6o8tnz-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ikj6o8tnz-nodejs 
